### ISSUE TITLE
Won't run on Ubuntu 20.10 amd64

### ISSUE THREAD

**Issue by HaaseIT** [willdoescode/nat#16]
Gives the following error message:

bash: /usr/local/bin/nat: Kann die Binärdatei nicht ausführen: Fehler im Format der Programmdatei

(sorry for german error message, means somthing like: cannot execute binary file: error in format).

I guess, some dependencies are missing that are not mentioned in the readme?

**Comment by willdoescode** [comment]
Linux is not currently supported in nat. I will reopen this thread if that changes.

**Comment by SubOptimal** [comment]
Why Linux should not supported? Which features are not working?

As a quick test the following worked for me on Debian bullseye

```
$ apt-get install rustc cargo
$ cd /tmp
$ git clone https://github.com/willdoescode/nat
$ cd /tmp/nat
$ cargo build
...
    Finished dev [unoptimized + debuginfo] target(s) in 30.63s
$ cd target/debug
$ ./nat
```
![grafik](https://user-images.githubusercontent.com/653288/97086853-2dece400-1626-11eb-89fc-f91888e6a298.png)

**Comment by willdoescode** [comment]
for other linux users nat did not seem to work I will add the steps you took to compile to the readme

**Comment by spikecodes** [comment]
@willdoescode I am on Manjaro, a fork of ArchLinux. I downloaded `nat` using the [package that I published to the AUR](https://aur.archlinux.org/packages/nat-git/) (arch user repository) and it works flawlessly for me:
![image](https://user-images.githubusercontent.com/19519553/97092067-8b1c7180-15f5-11eb-87b0-7114309954dc.png)

If you're wondering, the AUR package clones this repository and runs:
```shell
cargo build --release --locked --all-features --target-dir=target
```
Then puts the binary in `/usr/bin/` so users can run `nat` from their command line.
Another user reported that the build failed because of the `--locked` flag so I will probably remove that.
