### ISSUE TITLE
Comparison with Exa

### ISSUE THREAD

**Issue by ClementNerma** [willdoescode/nat#36]
Hi there,

First of all thanks for this project, it seems to have a lot of nice features compared to the basic `ls` :)

One thing I think could be great is to show a comparison with [Exa](https://github.com/ogham/exa), which is another `ls` replacement that existed for a long time (more than 5 years).

This way, potentiel users could see what benefits Nat delivers compared to Exa.

What do you think?

**Comment by apiening** [comment]
Just stumbled upon this project a few minutes ago, since it was mentioned at heise.de.
I'm evaluating nat vs. Exa for my own usage and I have the same question as you.
A few things I noticed right away:
- **Exa** is available for several package managers like **apt** and **brew**. This is of course a subject to change, since this project is much newer.
- **nat** does not have sorting per default, or at least I don't understand the way the output is ordered. I was also not able to enable sorting or change the sorting criteria. May be completely user fault. But **Exa** has sorting for me enabled right away.
- I found users reporting that **Exa** is often slower, or even much slower than **ls** or **tree**. It would be interesting to benchmark **nat** to see if it performs better.
- The optional header is not aligned to the output, which makes it unnecessary difficult to read. This has been mentioned here: https://github.com/willdoescode/nat/issues/35. **Exa** does not have this problem.
- Not all options of nat are shown by the quick help output from `nat --help`. For instance the parameter **-a** which enables listing of all files (including dot files) is not mentioned.
- Exa offers a tree view (Parameter **--tree**). As far as I've seen **nat** can't do that.

These are my findings after just a few minutes using both tools. Bare with me if I said something wrong due to my lack of research.

**Comment by willdoescode** [comment]
Currently nat does not have as many features as exa does but I am working on adding more and more every day. Obviously it will be hard to compete with a five year old tool but I think we could do it.

nat is on the arch package manager currently.
I'm working on adding sorting right now and a command line flag to disable it.
I have not done any speed comparisons with nat and exa yet.
I will fix the header.

-a is shown in the help menu
![Screen Shot 2020-10-26 at 08 10 09](https://user-images.githubusercontent.com/53620720/97190268-c12b3400-1762-11eb-8d8a-85c92da5a812.png)

nat currently does not have a --tree flag.
