### ISSUE TITLE
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value' 

### ISSUE THREAD

**Issue by v1nte** [willdoescode/nat#56]
/home/v1nte/.cargo/registry/src/github.com-1ecc6299db9ec823/natls-2.1.5/src/utils/file_times.rs:18:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by willdoescode** [comment]
I think this is an issue with the metadata in your files not including a creation date for some reason which is why it was a unwrap error on a None value. It should be fixed now because of [this](https://github.com/willdoescode/nat/commit/c21c5d876e396c53a6129135b5769ed146747baf) commit.
try updating natls with ```
cargo install natls
``` and if the issue persists I will try to find a different method to fix it.

**Comment by willdoescode** [comment]
[should be fixed because of this commit now](https://github.com/willdoescode/nat/commit/7675ba095ad40f18d9e2e3090826baccabd3c92b)
Thread closed.
